config/routes.rb
Rails.application.routes.draw do
    get '/main', to: 'top#main'
    get '/login', to: 'top#login'
    post '/login', to: 'top#create'
    delete '/logout', to: 'top#destroy'
    root 'users#index'
    get 'top/main', to:'top#main'
    resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
      
    end

    def login
        
    end    

    def create
        @user = User.find_by(uid: session_params[:uid])
        if @user && @user.authenticate(session_params[:password])
            session[:login_uid] = params[:uid]
            redirect_to top_main_path, notice: 'ログインしました'
        else
            render :login
        end
    end
    
    def destroy
        session.delete(:login_uid)
        redirect_to root_path
    end
    
    private
    def session_params
        params.require(:session).permit(:uid, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            redirect_to new_user_path, notice: "ユーザーを登録しました。"
        else
            render :new
        end
    end
    
    private
    
    def user_params
        params.require(:user).permit(:uid, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to 'ユーザー登録', new_user_path , class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, class: 'nav-link'%></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link'%></li>
      </ul>
    </header>
    
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<h1>ログイン</h1>
<%= form_with url: '/login', scope: :session, local:  true do |f|%>
  <div class="form-group">
    <%= f.label :uid, 'ユーザーID' %>
    <%= f.text_field :uid, class: 'form-control', id: 'session_uid'%>
  </div>
  
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control', id: 'session_password'%>
  </div>
  
  <%= f.submit 'ログイン', class: 'btn btn-primary'%>
<% end %>

app/views/top/main.html.erb
<h1>ログインしました。</h1>
<%= link_to 'ログアウト', logout_path, method: :delete %>

app/views/users/_form.html.erb
<%= form_for @user, url:  {action: :create} do |f| %>
  <div class="form-group">
    <%= f.label :uid, 'ユーザーID'%>
    <%= f.text_field :uid, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード'%>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit '登録', class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<p>ユーザーIDとパスワードを登録してください</p>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<%= render partial: 'form', locals: { person: @user} %>